apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-11-16T16:25:11Z"
  generateName: order-deployment-8b9765687-
  labels:
    framework: flask
    pod-template-hash: 8b9765687
    service: order
    tier: backend
  name: order-deployment-8b9765687-swvjf
  namespace: skubestore
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: order-deployment-8b9765687
    uid: 77c957ce-ca51-4f43-9de4-6bde797a01e5
  resourceVersion: "3790"
  uid: b8ec0a57-aa1b-4732-863b-7f5f5ac1ec6d
spec:
  containers:
  - env:
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: MYSQL_PASSWORD
          name: skubestore-secret
    envFrom:
    - configMapRef:
        name: skubestore-configmap
    image: noambenm/skubestore-order-service:v1.0
    imagePullPolicy: Always
    name: order-container
    ports:
    - containerPort: 5000
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5k9mw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - envFrom:
    - configMapRef:
        name: skubestore-configmap
    - secretRef:
        name: skubestore-secret
    image: noambenm/skubediver-divelog-init:v1.0-alpine3.20
    imagePullPolicy: Always
    name: init-container
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5k9mw
      readOnly: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5k9mw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-11-16T16:25:16Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-11-16T16:25:22Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-11-16T16:25:11Z"
    message: 'containers with unready status: [order-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-11-16T16:25:11Z"
    message: 'containers with unready status: [order-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-11-16T16:25:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: noambenm/skubestore-order-service:v1.1
    imageID: ""
    lastState: {}
    name: order-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "noambenm/skubestore-order-service:v1.1"
        reason: ImagePullBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5k9mw
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.49.2
  hostIPs:
  - ip: 192.168.49.2
  initContainerStatuses:
  - containerID: docker://954f7ffaf93f6491552abd26308a5a10c2aa2cc3e546dd6fd211bfdbb83de2c6
    image: noambenm/skubediver-divelog-init:v1.0-alpine3.20
    imageID: docker-pullable://noambenm/skubediver-divelog-init@sha256:7e187eef1876c2f7ca2e7cbce6108f9e3ee334fd9e5921366d6910e57247d7ab
    lastState: {}
    name: init-container
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://954f7ffaf93f6491552abd26308a5a10c2aa2cc3e546dd6fd211bfdbb83de2c6
        exitCode: 0
        finishedAt: "2024-11-16T16:25:22Z"
        reason: Completed
        startedAt: "2024-11-16T16:25:15Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5k9mw
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Pending
  podIP: 10.244.0.44
  podIPs:
  - ip: 10.244.0.44
  qosClass: BestEffort
  startTime: "2024-11-16T16:25:11Z"
