apiVersion: v1
kind: ConfigMap
metadata:
  name: skubestore-configmap
  namespace: skubestore
data:
  MYSQL_HOST: mysql-service.skubestore.svc.cluster.local
  MYSQL_USER: skubestore
  MYSQL_DATABASE: skubestore
